# Generated by Django 4.2.6 on 2023-11-13 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_course_rename_departement_student_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="ects",
            new_name="_ects",
        ),
    ]
