# Generated by Django 4.2.6 on 2024-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0011_remove_course__ects_course_ects"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
