# Generated by Django 4.2.6 on 2024-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
