# Generated by Django 4.2.6 on 2024-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_parameter_show_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(),
        ),
    ]
