# Generated by Django 4.2.6 on 2024-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_department_description_alter_parameter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='elective_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcours',
            name='mandatory_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
