# Generated by Django 4.2.6 on 2024-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_parcours_academic_base_ects_parcours_base_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='timetable_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
