# Generated by Django 4.2.6 on 2024-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_alter_department_timetable_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='end_comment',
            field=models.TextField(blank=True, default='Attention: Cette action est irréversible. Aucun changement ultérieur ne pourra être effectué sauf en cas de demande auprès de ton responsable de département.', null=True),
        ),
    ]
